id: IA05E5A55
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-16T12:47:03+00:00'
last_modified: '2022-06-10T05:01:04.606443+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN8015
  title: དཀར་ཁུང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    8C3F:
      image_group_id: I3CN8017
      title: Volume 1 of dkar khung /
      total_pages: 98
      order: 1
      base_file: 8C3F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
